name = "sanci-cloudflare-saas-starter"
compatibility_date = "2025-06-19"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "sanci-cloudflare-saas-starter-db"
database_id = "7a6e6a8e-d08d-4b3d-88fa-2f215ab9540b"
migrations_dir = "./drizzle"
